# ── Hostname ─────────────────────────────────
hostname=localhost
hostname-strict=false

# ── HTTP config ──────────────────────────────
http-port=8080

# ── Logging (optional, giúp debug) ───────────
log-level=INFO

spi-theme-cache-themes=false
spi-theme-cache-templates=false